-- Demo user id for local Supabase testing.
-- In a real product, use auth.uid() from the signed-in user instead.
\set demo_user_id '00000000-0000-0000-0000-000000000001'

insert into public.entertainment_cards (
  card_id,
  user_id,
  source_type,
  title,
  subtitle,
  description,
  content_category,
  mood_tags,
  duration_min,
  duration_max,
  energy_level,
  indoor_outdoor,
  prep_cost,
  people,
  budget_level,
  location_type,
  distance_level,
  reservation_required,
  ticket_required,
  weather_dependency,
  constraint_tags,
  status,
  eligible_for_draw,
  missing_fields,
  feedback_summary
) values
(
  '10000000-0000-0000-0000-000000000001',
  :'demo_user_id',
  'personal',
  '看《机器人之梦》',
  '安静低精力电影',
  '适合下班后在家看的一部电影。',
  'movie',
  array['quiet', 'relax'],
  90,
  105,
  'low',
  'indoor',
  'low',
  'solo',
  'low',
  'home',
  'none',
  false,
  false,
  'none',
  '{}',
  'active',
  true,
  '{}',
  '{"accept": 1}'
),
(
  '10000000-0000-0000-0000-000000000002',
  null,
  'preset',
  '附近公园散步 30 分钟',
  '轻户外恢复',
  '适合天气舒服、愿意出门时。',
  'walk',
  array['fresh', 'light'],
  30,
  45,
  'medium',
  'outdoor',
  'low',
  'solo',
  'free',
  'nearby',
  'short',
  false,
  false,
  'sunny_preferred',
  array['weather_sensitive'],
  'active',
  true,
  '{}',
  '{}'
),
(
  '10000000-0000-0000-0000-000000000003',
  :'demo_user_id',
  'personal',
  '打一局轻松解谜游戏',
  '短时、低准备',
  '适合不想出门但想有点互动的时候。',
  'game',
  array['relax', 'interactive'],
  20,
  40,
  'low',
  'indoor',
  'low',
  'solo',
  'free',
  'home',
  'none',
  false,
  false,
  'none',
  '{}',
  'active',
  true,
  '{}',
  '{}'
),
(
  '10000000-0000-0000-0000-000000000004',
  null,
  'preset',
  '看一个城市展览',
  '需要出门和购票',
  '适合周末下午。',
  'exhibition',
  array['fresh', 'inspiration'],
  120,
  180,
  'medium',
  'indoor',
  'medium',
  'solo',
  'medium',
  'citywide',
  'medium',
  true,
  true,
  'none',
  array['transport_needed', 'ticket_required'],
  'active',
  true,
  '{}',
  '{}'
)
on conflict (card_id) do update set
  title = excluded.title,
  updated_at = now();

insert into public.user_memory (
  user_id,
  preference_memory,
  explicit_profile
) values (
  :'demo_user_id',
  '{
    "category_weights": {
      "movie": 0.4,
      "game": 0.2,
      "walk": 0.1,
      "exhibition": 0
    },
    "duration_preference": [30, 120],
    "indoor_outdoor_preference": "indoor"
  }',
  '{
    "default_budget_level": "low",
    "dietary_constraints": [],
    "travel_preference": "short",
    "user_editable": true
  }'
)
on conflict (user_id) do update set
  preference_memory = excluded.preference_memory,
  explicit_profile = excluded.explicit_profile,
  updated_at = now();
