insert into public.entertainment_cards (
  card_id,
  user_id,
  source_type,
  source_asset,
  title,
  subtitle,
  description,
  content_category,
  mood_tags,
  duration_min,
  duration_max,
  energy_level,
  indoor_outdoor,
  prep_cost,
  people,
  budget_level,
  location_type,
  distance_level,
  reservation_required,
  ticket_required,
  weather_dependency,
  constraint_tags,
  status,
  eligible_for_draw,
  missing_fields,
  quality_score,
  rule_version,
  score_version,
  notes
) values
  ('00000000-0000-4000-8000-000000000101', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '看一部收藏很久的温柔电影', '不需要做功课的安静片刻', '适合低精力夜晚，选一部早就想看的电影，准备一杯饮品后开始。', 'movie', array['relax','quiet','home'], 90, 120, 'low', 'indoor', 'low', 'solo', 'low', 'home', 'none', false, false, 'indoor_friendly', array['screen_time'], 'active', true, array[]::text[], 88, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000102', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '补一集轻松下饭剧', '短一点，也能进入故事', '从正在追或一直想看的剧集中选一集，适合吃饭后轻松收尾。', 'series', array['relax','home','casual'], 35, 55, 'low', 'indoor', 'low', 'solo', 'low', 'home', 'none', false, false, 'indoor_friendly', array['screen_time'], 'active', true, array[]::text[], 86, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000103', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '读完一本书的一个章节', '不用追求很多页', '选一本已经放在书架或电子书里的作品，只读一个自然章节。', 'book', array['quiet','focus','home'], 25, 45, 'low', 'indoor', 'low', 'solo', 'free', 'home', 'none', false, false, 'indoor_friendly', array[]::text[], 'active', true, array[]::text[], 84, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000104', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '听完一集轻松播客', '让耳朵接管一会儿', '选择一集 30 到 45 分钟的访谈、故事或娱乐播客，可以边收拾边听。', 'music', array['relax','audio','casual'], 30, 45, 'low', 'flexible', 'low', 'solo', 'free', 'home_or_nearby', 'short', false, false, 'flexible', array[]::text[], 'active', true, array[]::text[], 84, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000105', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '整理一个今晚歌单', '只为此刻的心情服务', '打开常用音乐 App，按今晚状态挑 8 到 12 首歌。', 'music', array['relax','creative','home'], 20, 35, 'low', 'indoor', 'low', 'solo', 'free', 'home', 'none', false, false, 'indoor_friendly', array[]::text[], 'active', true, array[]::text[], 82, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000106', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '玩一局轻量单机游戏', '可暂停，不绑社交局', '选择一款能随时暂停的休闲游戏，给自己一个完整小回合。', 'game', array['playful','home','relax'], 25, 45, 'low', 'indoor', 'low', 'solo', 'free', 'home', 'none', false, false, 'indoor_friendly', array['screen_time'], 'active', true, array[]::text[], 86, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000107', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '约朋友打一局线上桌游', '轻社交，不需要出门', '选择规则熟悉、时长可控的线上桌游或小游戏，约一两位朋友。', 'game', array['social','playful','home'], 45, 75, 'medium', 'indoor', 'medium', 'group', 'free', 'online', 'none', false, false, 'indoor_friendly', array['coordination_needed'], 'active', true, array[]::text[], 82, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000108', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '去附近安静地散步一圈', '只走熟悉安全路线', '选择熟悉、照明良好的路线，走一圈后回家，不设运动目标。', 'walk', array['active','quiet','nearby'], 25, 45, 'medium', 'outdoor', 'low', 'solo', 'free', 'nearby', 'short', false, false, 'weather_sensitive', array['safe_route','outdoor'], 'active', true, array[]::text[], 84, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000109', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '去一家附近咖啡店坐坐', '换个地方轻轻待一会儿', '找一家路程短、评价稳定的咖啡店，点一杯饮品坐 40 分钟。', 'cafe', array['relax','nearby','solo'], 45, 75, 'medium', 'outdoor', 'medium', 'solo', 'low', 'nearby', 'short', false, false, 'weather_sensitive', array['transport_optional'], 'active', true, array[]::text[], 82, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000110', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '试一家收藏的简餐店', '把种草变成一顿饭', '从收藏夹里选一家不用排很久的简餐店，适合晚饭或周末午后。', 'restaurant', array['food','nearby','casual'], 60, 90, 'medium', 'outdoor', 'medium', 'solo', 'medium', 'nearby', 'short', false, false, 'weather_sensitive', array['possible_queue'], 'active', true, array[]::text[], 82, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000111', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '做一份简单甜品或饮品', '厨房里的小小娱乐', '选一个步骤少、材料常见的饮品或甜品，只做一人份。', 'home_activity', array['creative','home','food'], 30, 60, 'medium', 'indoor', 'medium', 'solo', 'low', 'home', 'none', false, false, 'indoor_friendly', array['kitchen'], 'active', true, array[]::text[], 80, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000112', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '看一个小型展览', '用半天换一段新鲜感', '选择交通方便、展期明确的小型展览，提前确认开放时间。', 'exhibition', array['culture','quiet','outdoor'], 90, 150, 'medium', 'outdoor', 'medium', 'solo', 'medium', 'city', 'medium', false, true, 'weather_sensitive', array['ticket_needed','transport_needed'], 'active', true, array[]::text[], 84, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000113', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '逛一次书店或音像店', '不买也可以', '找一家路线简单的书店、唱片店或文创店，慢慢逛一圈。', 'shopping', array['quiet','nearby','culture'], 45, 90, 'medium', 'outdoor', 'low', 'solo', 'low', 'nearby', 'short', false, false, 'weather_sensitive', array['transport_optional'], 'active', true, array[]::text[], 80, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000114', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '拼一小段积木或拼图', '只完成一个小区域', '把积木、拼图或模型拿出来，只推进一个可见的小部分。', 'craft', array['quiet','creative','home'], 30, 60, 'low', 'indoor', 'low', 'solo', 'free', 'home', 'none', false, false, 'indoor_friendly', array[]::text[], 'active', true, array[]::text[], 82, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000115', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '给朋友发一个轻松邀约', '约一件很小的事', '挑一个关系舒服的人，发出一次低压力邀约，比如咖啡、散步或一起看电影。', 'social', array['social','warm','planning'], 10, 20, 'medium', 'flexible', 'low', 'pair', 'free', 'online', 'none', false, false, 'flexible', array['coordination_needed'], 'active', true, array[]::text[], 78, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000116', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '整理一页娱乐愿望清单', '只保留真的想做的', '把最近种草的电影、展览、店铺或游戏整理成一页，删掉已经没兴趣的。', 'home_activity', array['planning','quiet','home'], 20, 35, 'low', 'indoor', 'low', 'solo', 'free', 'home', 'none', false, false, 'indoor_friendly', array[]::text[], 'active', true, array[]::text[], 76, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000117', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '看一场线上脱口秀或演出片段', '不用买票也能换心情', '选择一段 30 到 60 分钟的线上演出、喜剧或音乐现场回放。', 'event', array['playful','home','relax'], 30, 60, 'low', 'indoor', 'low', 'solo', 'free', 'online', 'none', false, false, 'indoor_friendly', array['screen_time'], 'active', true, array[]::text[], 80, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000118', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '翻一本画册或摄影集', '让眼睛慢慢休息', '拿出一本画册、摄影集或设计书，按图片随意翻看。', 'book', array['quiet','visual','home'], 20, 40, 'low', 'indoor', 'low', 'solo', 'free', 'home', 'none', false, false, 'indoor_friendly', array[]::text[], 'active', true, array[]::text[], 78, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000119', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '做一次房间里的迷你观影夜', '把普通电影变成仪式感', '调暗灯光，准备零食，选一部 90 分钟左右的片子认真看完。', 'movie', array['home','relax','ritual'], 90, 120, 'low', 'indoor', 'medium', 'solo', 'low', 'home', 'none', false, false, 'indoor_friendly', array['screen_time'], 'active', true, array[]::text[], 84, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000120', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '找一家甜品店打卡', '只为了好吃和开心', '选择交通短、营业时间明确的甜品店，适合和朋友或自己去。', 'cafe', array['food','nearby','playful'], 45, 75, 'medium', 'outdoor', 'medium', 'flexible', 'medium', 'nearby', 'short', false, false, 'weather_sensitive', array['possible_queue'], 'active', true, array[]::text[], 78, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000121', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '去公园坐一会儿', '不运动，只透口气', '选择熟悉、白天更适合的公园或公共空间，坐一会儿再回来。', 'walk', array['quiet','nearby','relax'], 30, 60, 'low', 'outdoor', 'low', 'solo', 'free', 'nearby', 'short', false, false, 'weather_sensitive', array['safe_route','daytime_better','outdoor'], 'active', true, array[]::text[], 78, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000122', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '和朋友云同步看一集剧', '一起吐槽更快乐', '约定同一集同时开始，用语音或消息轻松聊天。', 'series', array['social','home','playful'], 40, 60, 'medium', 'indoor', 'medium', 'pair', 'free', 'online', 'none', false, false, 'indoor_friendly', array['coordination_needed','screen_time'], 'active', true, array[]::text[], 80, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000123', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '试一个手帐或贴纸拼贴', '把碎片变成一页', '拿出纸本、贴纸或照片，做一页不用完美的拼贴。', 'craft', array['creative','quiet','home'], 25, 50, 'low', 'indoor', 'low', 'solo', 'low', 'home', 'none', false, false, 'indoor_friendly', array[]::text[], 'active', true, array[]::text[], 78, 'filter_v1', 'score_v1', '冷启动预置卡'),
  ('00000000-0000-4000-8000-000000000124', null, 'preset', '{"source":"preset_v1","curation":"manual"}', '看一部短纪录片', '用一个小时认识一件事', '选择一部主题轻松、长度不超过一小时的纪录片，不做学习任务。', 'movie', array['quiet','culture','home'], 40, 65, 'low', 'indoor', 'low', 'solo', 'free', 'home', 'none', false, false, 'indoor_friendly', array['screen_time'], 'active', true, array[]::text[], 80, 'filter_v1', 'score_v1', '冷启动预置卡')
on conflict (card_id) do update set
  source_asset = excluded.source_asset,
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  content_category = excluded.content_category,
  mood_tags = excluded.mood_tags,
  duration_min = excluded.duration_min,
  duration_max = excluded.duration_max,
  energy_level = excluded.energy_level,
  indoor_outdoor = excluded.indoor_outdoor,
  prep_cost = excluded.prep_cost,
  people = excluded.people,
  budget_level = excluded.budget_level,
  location_type = excluded.location_type,
  distance_level = excluded.distance_level,
  reservation_required = excluded.reservation_required,
  ticket_required = excluded.ticket_required,
  weather_dependency = excluded.weather_dependency,
  constraint_tags = excluded.constraint_tags,
  status = excluded.status,
  eligible_for_draw = excluded.eligible_for_draw,
  missing_fields = excluded.missing_fields,
  quality_score = excluded.quality_score,
  rule_version = excluded.rule_version,
  score_version = excluded.score_version,
  notes = excluded.notes,
  updated_at = now();
